notifications:
    email: false

language: python

matrix:
    include:
        - os: linux
          dist: trusty
          python: 3.4
        - os: linux
          dist: trusty
          python: 3.5


# command to install dependencies
install: 
  - python setup.py install
# command to run tests
script: py.test
