# https://ci.appveyor.com/project/jkbrzt/httpie
build: false

environment:
  matrix:
    # Python 3.4 is not supported due to MSVC version
    # - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  # FIXME: updating pip fails with PermissionError
  # - "%PYTHON%/Scripts/pip.exe install -U pip setuptools"
  - "%PYTHON%/Scripts/pip.exe install -e ."

test_script:
  - "%PYTHON%/python.exe setup.py test"